import = ["~/.config/alacritty/themes/vscode.toml"]

[env]
TERM = "xterm-256color"
# WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.normal]
family = "JetbrainsMono Nerd Font Mono"
style = "Regular"


[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "Both"
dynamic_padding = true

[window.padding]
x = 4
y = 4

[colors]
draw_bold_text_with_bright_colors = true

# [colors.cursor]
# text = "#FFFFFF"
# cursor = "#1E1E1E"


[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"
