import = ["~/.config/alacritty/themes/vscode.toml"]

[env]
TERM = "xterm-256color"
# WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 18
# offset.y = 8 

[font.normal]
# family = "JetbrainsMono Nerd Font Mono"
family = "MesloLGM Nerd Font Mono"
# family = "Geist Mono"
style = "Regular"


[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "Both"
dynamic_padding = true

[window.padding]
x = 4
y = 4

[colors]
draw_bold_text_with_bright_colors = true

# [colors.cursor]
# text = "#FFFFFF"
# cursor = "#1E1E1E"


[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"
